---
    name: "tagged-release"
    
    on:
      push:
        tags:
          - "v*.*.*"
    
    jobs:
      tagged-release:
        name: "Tagged Release"
        runs-on: "ubuntu-latest"
    
        steps:
          - name: "Checkout"
            uses: "actions/checkout@v2"
          - name: "Build"
            run: |
              make all
              echo "done!"
          - name: "Zip binaries with tag"
            run: |
              zip -r binaries-${{ github.ref }}.zip ./bin/crc64 ./bin/sha1024 ./bin/md7 ./bin/ush
              echo "done!"
    
          - uses: "marvinpinto/action-automatic-releases@latest"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              files: |
                bin/crc64
                bin/sha1024
                bin/md7
                bin/ush
                binaries.zip